#!/bin/sh

#    Periwinkle - A MPD client with tight integration with dmenu and libnotify.
#    Copyright (C) 2023 Fen
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

# -------------------
# CONFIGURATION STUFF
# -------------------


# Here's the config for Periwinkle
# You'll have to change this before you do anything else

# ---
# MPD
# ---
#
# Choose where to point

#MPD_Host=localhost
#MPD_Port=6600

# Choose your music directory

#Directory_MusicFolder=$HOME/Music

# Which menu do you want to use?
# You can choose between dmenu and wmenu.
# Use dmenu if you're using X11 and wmenu if you're using Wayland.
# This option does nothing on macOS

#UseThisMenuProgram=dmenu

# -----
# APPEARANCE
# -----
#
# In dwm, usually the following equivalents for dmenu coloring are:
# Bar_Font = dmenufont
# Color_Background = col_gray1
# Color_Foreground = col_gray3
# Color_SelectedBackground = col_gray4
# Color_SelectedForeground = col_cyan

#Bar_Font="Sans Serif":size=10
#Color_Background=#5B544C
#Color_Foreground=#E4E3E0
#Color_SelectedBackground=#DA2A47
#Color_SelectedForeground=#E4E3E0

# Location of DMENU, if it's at the bottom or top.
# By default it's at the bottom

#Bar_Position=bottom

# Use Nerd Fonts for more eye candy
# Warning: This option is not supported on macOS.
#UseNerdFont=true

# ----------------
# PREVIEW SETTINGS
# ----------------
#
# Choose where to save the image previews

#Directory_AlbumCover=$HOME/periwinkle

# ---------------------
# NOTIFICATION SETTINGS
# ---------------------
#
# Notify timeout in seconds
# Set 0 for no timeout

#Notify_Timeout=5

# Format the notification
# Set the appearance of the notification to your liking.
# Side note: %datep% is a variant of %date%, what it does is that if the metadata doesn't contain any date, it hides the parenthesis. Otherwise, if it contains a year, it shows them.

#Notify_TitlePlay='%stateicon% "%title%"'
#Notify_Line1Play="from %album% %datep%"
#Notify_Line2Play="by %album% %datep%"


# Set the title to appear when the queue is completely stopped

#Notify_TitleStop="%stateicon% Stopped"

# Set the title to appear when the Music Player Daemon is not running

#Notify_TitleOffline="%stateicon% Offline"

# Use formatting behavior from CLI, similar to previous versions of Periwinkle
# So what this does is basically when a song has no title, it displays the filename instead. And if there's no artist, it shows "Unknown Artist"
# By default, it's set on "false"

#Notify_FillEmptyTags=false

# ----------------
# PREVIEW SETTINGS
# ----------------
# 
# Choose the hash that you would like to use to save the image previews
# This is useful to keep every single album unique.
# For example, if you had Weezer self-titled albums with the same album name in their metadata, it should be able to differentiate them to show the correct album cover because they have a different metadata for the year and artist. If you have proper metadata for every album then it should work as expected
#
# Options: 
# none | md5 | sha256 | sha512 | base64
# The default is sha256

#UseHash=sha256

# Down here is code!

pw_Help() {
	pw_SendMessage Info "Periwinkle - The cutest MPD client

	This is a CLI and also a semi-GUI client that can
	be integrated into a DWM desktop by the use of
	dunst and dmenu, if you'd like.

	Usage: periwinkle [<command> <arguments> ... <more args>]

	Fetch Commands
		add <file> - Adds a song from the music dir to the playlist
		delete <int song> - Removes a song from the playlist
		list <metadata arg1> [<metadata arg2> <search term>] - Fetches a list of songs based on the metadata input by the user

	Playback Commands
		pause - Toggles between pause and play
		play - Play the current song
		stop - Stops the playlist completely
		prev, previous - Goes to the previous song on the queue
		next, forward - Goes to the next song on the queue
		setvol <0 - 100> - Sets the volume
		seek <num> - Seeks to a certain point of the song
		single <0-1 or oneshot> - Sets single mode
		random <0-1> - Sets random mode
		repeat <0-1> - Sets repeat mode
		consume <0-1> - Sets consume mode

	Playlist Commands
		crossfade <int> - Sets a crossfade between songs
		shuffle - Shuffles the playlist
		save <string playlist name> - Saves the playlist as a file
		rm <string playlist name> - Deletes a saved playlist
		playlist - Shows the current playlist and song IDs
		delete - Removes a song from the current playlist

	Database Commands
		update - Updates the MPD database

	Periwinkle Commands
		menu - Shows the dmenu prompt directly
		info - Report version of Periwinkle, and licensing information
		print <\%title% %artist% %album% %date% %datep% %songid% %state% %stateicon%> - Command that works like mpc's --format flag.
		The point of the command above is to print current song info to stdout in a similar manner to echo.

	Dmenu Exclusive Commands
		cli <cmd> - Runs a CLI command within dmenu

	Advanced Commands
		daemon - Run as a daemon to show song notifications on the background (experimental)
		statsfornerds - Shows some environment variables related to Periwinkle
		console - Pulls an interactive MPD control terminal (advanced)
		direct - Sends commands to MPD without going into the interactive terminal

	If you want to change the settings for this client, tinker with the periwinkle script.
	All documentation is on the script."
}

pw_AboutProgram() {
	pw_SendMessage Info "
    Periwinkle - The cutest MPD client
    Version:

    Copyright (C) 2023 Fen

    Contributors: ChatGPT, Barrucadu

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
	"
}

pw_SendMessage() {
	case $1 in
		"ErrUnknownCommand")
			printf "[%s - ERR] '%s' is not a known command >.<\n" "$(date)" "$2";;
	
		"ErrInvalidInteger")
			printf "[%s - ERR] '%s' is not a valid integer -w-\n" "$(date)" "$2";;

		"ErrInvalidNumber")
			printf "[%s - ERR] '%s' is not a valid number -w-\n" "$(date)" "$2";;

		"ErrFewArguments")
			printf "[%s - ERR] Not enough arguments... ;w;\n" "$(date)" "$2";;

		"ErrManyArguments")
			printf "[%s - ERR] T-That's too many arguments!! >w<\n" "$(date)" "$2";;

		"ErrWrongArguments")
			printf "[%s - ERR] Wrong arguments for this command... :<\n" "$(date)" "$2";;

		"ErrPlaylistClear")
			printf "[%s - ERR] You can't %s if you have no songs in your queue or if the queue is stopped! >:3\n" "$(date)" "$2";;

		"Warn")
			printf "[%s - WARN]" "$(date)" 
			;;

		"Info")
			printf "[%s - INFO]" "$(date)" 
			;;

		"Exception" | "" | *)
			printf "[%s - ERR]" "$(date)" 
			;;
	esac

	case $1 in
		"Info" | "Warn" | "Error" | "Exception")
			if [ -n "$2" ]; then
				printf " %s\n" "$2"
			else
				printf " Your message goes here.\n"
			fi
	esac

	return
}

# Placeholder default check. Will be more sophisticated in the future.
pw_FillInTheBlanks() {

	if [ -z "$MPD_Host" ]; then
		MPD_Host=localhost
	fi
	
	if [ -z "$MPD_Port" ]; then
		MPD_Port=6600
	fi

	if [ -z "$Notify_Timeout" ]; then
		Notify_Timeout=5	
	fi

	if [ -z "$Notify_TitlePlay" ]; then
		if [ "$pw_CurrentOperatingSystem" = "Darwin" ]; then
			Notify_TitlePlay='%stateicon%'
		else
			Notify_TitlePlay='%stateicon% "%title%"'
		fi
	fi

	if [ -z "$Notify_Line1Play" ]; then
		if [ "$pw_CurrentOperatingSystem" = "Darwin" ]; then
			Notify_Line1Play='%title%'
		else
			Notify_Line1Play='by %artist%'
		fi
	fi

	if [ -z "$Notify_Line2Play" ]; then
		if [ "$pw_CurrentOperatingSystem" = "Darwin" ]; then
			Notify_Line2Play="%artist%""'"'s "%album%" %datep%'
		else
			Notify_Line2Play='from "%album%" %datep%'
		fi
	fi

	if [ -z "$Notify_TitleStop" ]; then
		if [ "$pw_CurrentOperatingSystem" = "Darwin" ]; then
			Notify_TitleStop="Stopped"
		else
			Notify_TitleStop="%stateicon% Stopped"
		fi
	fi

	if [ -z "$Notify_TitleOffline" ]; then
		if [ "$pw_CurrentOperatingSystem" = "Darwin" ]; then
			Notify_TitleOffline="Offline"
		else
			Notify_TitleOffline="%stateicon% Offline"
		fi
	fi

	if [ -z "$Notify_FillEmptyTags" ]; then
		Notify_FillEmptyTags=false	
	fi

	if [ -z "$Notify_ExtraButtons" ]; then
		Notify_ExtraButtons=false
	fi

	if [ -z "$Bar_Position" ]; then
		Bar_Position=top
	fi

	if [ -z "$Bar_Font" ]; then
		Bar_Font="Sans Serif":size=10
	fi
	
	if [ -z "$Color_Background" ]; then
		Color_Background=#C0C0C0
	fi

	if [ -z "$Color_Foreground" ]; then
		Color_Foreground=#000000
	fi

	if [ -z "$Color_SelectedBackground" ]; then
		Color_SelectedBackground=#000080
	fi

	if [ -z "$Color_SelectedForeground" ]; then
		Color_SelectedForeground=#FFFFFF
	fi

	if [ -z "$Directory_AlbumCover" ]; then
		Directory_AlbumCover=$HOME/periwinkle	
	fi

	if [ -z "$Directory_MusicFolder" ]; then
		Directory_MusicFolder=$HOME/Music	
	fi

	if [ -z "$UseNerdFont" ]; then
		if [ "$pw_CurrentOperatingSystem" = "Darwin" ]; then
			UseNerdFont=false
		else
			UseNerdFont=true
		fi
	elif [ "$UseNerdFont" = "true" ] && [ "$pw_CurrentOperatingSystem" = "Darwin" ]; then
		pw_SendMessage Warn "While using Periwinkle on macOS, Nerd Fonts are not supported. Here be dragons."
	fi

	if [ "$pw_CurrentOperatingSystem" = "Darwin" ]; then
		UseThisMenuProgram=dmenu-mac
	elif [ -z "$UseThisMenuProgram" ] && [ "$pw_CurrentOperatingSystem" != "Darwin" ]; then
		UseThisMenuProgram=dmenu
	fi

	Notify_TitlePlaySave=$Notify_TitlePlay
	Notify_Line1PlaySave=$Notify_Line1Play
	Notify_Line2PlaySave=$Notify_Line2Play

}

# Function to check if a value is a number
pw_isPositiveNumber() {
	if [ "$1" -gt 0 ]; then
		return 0 # It's a positive number
	else
		return 1 # It's not a positive number or it contains non-numeric characters
	fi
}

# Function to check if the integer is within the desired range
pw_isNumberInRange() {
	if [ "$1" -gt "$MINIMUMVAL" ] && [ "$1" -lt "$MAXIMUMVAL" ]; then
		return 0
	else
		return 1
	fi
}

pw_CheckNumber() {
	# Read input and validate it until a valid integer in the range is provided
	case $2 in
		"inRange")
			if ! pw_isNumberInRange "$1"; then
				# Set the variable with the validated integer
				pw_SendMessage ErrInvalidInteger "$1"
			fi;;

		"isPositive")
			if ! pw_isPositiveNumber "$1"; then
				pw_SendMessage ErrInvalidNumber "$1"
			fi;;

		*)
			pw_SendMessage Error "$1"
			pw_SendMessage Error "DEBUG INFO: Invalid arguments for this function" 
			pw_SendMessage Error "If you see this message, please open a issue about it.";;
	esac
}

pw_SpawnNotification() {
	# $1 = Title
	# $2 = Subtitle 
	# $3 = Message
	# $4 = Icon

	pw_NotificationID=27072

	case $pw_CurrentOperatingSystem in
		"Darwin")
		NotificationActionSelected="$(alerter	-title "$1" \
												-subtitle "$2" \
												-message "$3" \
												-contentImage "$4" \
												-group "$pw_NotificationID" \
												-sender "$pw_NotificationID" \
												-timeout "$(($Notify_Timeout / 1000))")"
		;;
		
		*)
		NotificationActionSelected=$(notify-send	-a "Periwinkle" \
													-t "$Notify_Timeout" \
													-u low \
													-r "$pw_NotificationID" "$1" "$2\n$3" \
													-i "$4" \
													--action open=Show 2>/dev/null)
		;;
	esac

	if    [ -z "$NotificationActionSelected" ] \
	   || [ "$NotificationActionSelected" = "@TIMEOUT" ] \
	   || [ "$NotificationActionSelected" = "@CLOSED" ]; then
		return 0

	elif [ -s /tmp/pw_daemonmode ]; then
		pw_MenuOptions daemon

	else
		pw_MenuOptions "$NotificationActionSelected"

	fi
		
}

# Clean the stinky output
pw_CleanOutput() {
	awk '!/^OK.*$/'
}

# Function to send commands to MPD which is netcat-agnostic
pw_MPDCommand() { 
	(
	printf "%s\n" "$1" "close";
	sleep 0.01
	) | nc "$MPD_Host" "$MPD_Port"; 
}

pw_ReloadMetadata() {
	
	case $1 in
		"OnlineStatus")
			pw_MPDCommand console > /dev/null 2>&1

			if [ $? = 1 ]; then
				pw_MPDIsOnline=false
			else
				pw_MPDIsOnline=true
			fi;;

		"Title")
			title="$(printf "%s" "$stats" | awk -F ': ' '/^Title:/ { sub(/^Title: /, ""); print }')"
			titlesave="$title"

			if [ -z "$title" ]; then
				title="$mpc_file"
			fi;;

		"Artist")
			artist="$(printf "%s" "$stats" | awk -F ': ' '/^Artist:/ { sub(/^Artist: /, ""); print }')"
			artistsave="$artist"

			if [ -z "$artist" ]; then
				artist="Unknown Artist"
			fi;;

		"Album")
			album="$(printf "%s" "$stats" | awk -F ': ' '/^Album:/ { sub(/^Album: /, ""); print }')";;

		"Date")
			date="$(printf "%s" "$stats" | awk -F ': ' '/^Date:/ { sub(/^Date: /, ""); print }')"
			unprocesseddate=$date
		
			if [ -z "$date" ]; then
				date=""
			else
    			date="($date)"
			fi;;

		"SongId")
			songid="$(printf "%s" "$stats2" | awk -F ': ' '/^song:/ { sub(/^song: /, ""); print }')";;

    	"Time")
        rawtimevar="$(printf "%s" "$stats2" | awk -F ': ' '/^time:/ { sub(/^time: /, ""); print }')"
		totalduration="$(printf "%s" "$stats" | awk -F ': ' '/^Time:/ { sub(/^Time: /, ""); print }')"

		if [ -z "$rawtimevar" ] && [ -n "$totalduration" ]; then
			elapsedtime=0
		else
			elapsedtime="${rawtimevar%:*}"   # part before colon
		fi
		;;

		"State")
			state="$(printf "%s" "$stats2" | awk -F ': ' '/^state:/ { sub(/^state: /, ""); print }')"
			if [ "$pw_MPDIsOnline" = "true" ]; then
				if [ "$UseNerdFont" = "true" ]; then
					if [ "$state" = "stop" ]; then
						NOTIFYSEND_STATUS=""
						OPPSTATUS=""
						OPPSTATUS2=""
					elif [ "$state" = "pause" ]; then
						NOTIFYSEND_STATUS=""
						OPPSTATUS=""
						OPPSTATUS2=""
					elif [ "$state" = "play" ]; then
						NOTIFYSEND_STATUS=""
						OPPSTATUS=""
						OPPSTATUS2=""
					fi
				else
					if [ "$state" = "stop" ]; then
						NOTIFYSEND_STATUS="Stopped"
						OPPSTATUS="Play"
						OPPSTATUS2=""
					elif [ "$state" = "pause" ]; then
						NOTIFYSEND_STATUS="Paused"
						OPPSTATUS="Play"
						OPPSTATUS2="Stop"
					elif [ "$state" = "play" ]; then
						NOTIFYSEND_STATUS="Playing"
						OPPSTATUS="Pause"
						OPPSTATUS2="Stop"
					fi
				fi
			else
				if [ "$UseNerdFont" = "true" ]; then
					NOTIFYSEND_STATUS=""
				else
					NOTIFYSEND_STATUS="Offline"
				fi
        OPPSTATUS=""
        OPPSTATUS2=""
        state="offline"
			fi;;

		"RefreshVariables")
			stats="$(pw_MPDCommand currentsong | tr -d '\r')"
			stats2="$(pw_MPDCommand status | tr -d '\r')"
			mpc_file="$(printf "%s" "$stats" | awk -F ': ' '/^file:/ {print $2}' | awk '{$1=$1};1')"
			filename="$Directory_MusicFolder"'/'"$mpc_file";;

		"SetAlbumCover")
			case $UseHash in
				"none")
					previewname="$Directory_AlbumCover"/"$album $date.png";;
				"md5")
					previewname="$Directory_AlbumCover"/"$(printf "%s %s" "$album" "$date" | md5sum | cut -d' ' -f1)".png;;
				"base64")
					previewname="$Directory_AlbumCover"/"$(printf "%s %s" "$album" "$date" | base64 | cut -d' ' -f1)".png;;
				"sha512")
					previewname="$Directory_AlbumCover"/"$(printf "%s %s" "$album" "$date" | sha512sum | cut -d' ' -f1)".png;;
				"sha256" | "" | *)
					previewname="$Directory_AlbumCover"/"$(printf "%s %s" "$album" "$date" | sha256sum | cut -d' ' -f1)".png;;	
			esac

			[ -e "$previewname" ] || 
			ffmpeg -y -i "$filename" -an -vf scale=128:128 "$previewname" > /dev/null 2>&1;;

		"All")
			pw_ReloadMetadata OnlineStatus
			pw_ReloadMetadata RefreshVariables
			pw_ReloadMetadata Title
			pw_ReloadMetadata Artist
			pw_ReloadMetadata Album
			pw_ReloadMetadata Date
			pw_ReloadMetadata SongId
			pw_ReloadMetadata State
			pw_ReloadMetadata Time
			pw_ReloadMetadata SetAlbumCover;;
	esac

	return 
	
}

pw_Refresh() {
	pw_ReloadMetadata OnlineStatus
	pw_ReloadMetadata RefreshVariables
	pw_ReloadMetadata State

	if [ "$CurrentState" != "$state" ] || [ -z "$CurrentState" ]; then
		pw_ReloadMetadata State
		CurrentState=$state
	fi

	if [ "$mpc_file" != "$CurrentFile" ] || [ -z "$CurrentFile" ]; then

		# Every attribute changes except for the title, it is unknown what causes this bug
		# So in the meantime, this is here until a fix is found for this
		# Feel free to experiment
	
		# My theory is that it's because of race conditions... yet again
		# This program has a lot of fucking issues with race conditions

		pw_ReloadMetadata Title
		pw_ReloadMetadata Date

		if [ "$CurrentTitle" != "$title" ] || [ -z "$CurrentTitle" ]; then	
			pw_ReloadMetadata Title
			CurrentTitle=$title
		fi

		if [ "$CurrentArtist" != "$artist" ] || [ -z "$CurrentArtist" ]; then
			pw_ReloadMetadata Artist
			CurrentArtist=$artist
		fi

		if [ "$CurrentAlbum" != "$album" ] || [ -z "$CurrentAlbum" ]; then
			pw_ReloadMetadata Album
			CurrentArtist=$album
		fi

		if [ "$CurrentDate" != "$date" ] || [ -z "$CurrentDate" ]; then
			pw_ReloadMetadata Date
			CurrentDate=$date
		fi

		if [ "$CurrentSongId" != "$songid" ] || [ -z "$CurrentSongId" ]; then
			pw_ReloadMetadata SongId
			CurrentSongId=$songid
		fi

		pw_ReloadMetadata SetAlbumCover
		CurrentFile="$mpc_file"

	fi 

	return 0
}

pw_SpawnMenu() {	
	case $UseThisMenuProgram in
		"dmenu-mac")
			dmenu-mac -p "$DMENU_TITLE";;

		"wmenu")
			wmenu -i -p "$DMENU_TITLE" -N "$Color_Background" -n "$Color_Foreground" \
				  -S "$Color_SelectedBackground" -s "$Color_SelectedForeground";;

		"dmenu" | *)
			dmenu "$Bar_Position" -i -p "$DMENU_TITLE" -fn "$Bar_Font" \
				  -nb "$Color_Background" -nf "$Color_Foreground" -sb \
				  "$Color_SelectedBackground" -sf "$Color_SelectedForeground";;			
	esac
}

pw_MPDCommandButFiltered() {

    arglist="$1"
     
    [ "$2" != "" ] &&                   arglist="$arglist "$2""
    
    [ "$3" != "" ] && [ "$4" = "" ]  && arglist="$arglist \"$3\""
    
    [ "$3" != "" ] && [ "$4" != "" ] && arglist="$arglist $3 \"$4\""

    [ "$1" = "add" ] || [ "$1" = "save" ] || [ "$1" = "rm" ] && arglist="$1 \"$2\""
    
    pw_MPDCommand "$arglist" | pw_CleanOutput
}

pw_UserSelection() { 
	
	if [ "$pw_MPDIsOnline" = "false" ]; then
		Notify_TitlePlay="$Notify_TitleOffline"
		Notify_Line1Play=""
		if [ "$pw_CurrentOperatingSystem" = "Darwin" ]; then
			Notify_Line2Play="The Music Player Daemon is currently not running."
		else
			Notify_Line2Play=""
		fi
	elif [ -z "$mpc_file" ]; then
		Notify_TitlePlay="$Notify_TitleStop"
		Notify_Line1Play=""
		if [ "$pw_CurrentOperatingSystem" = "Darwin" ]; then
			Notify_Line2Play="The playlist is currently stopped."
		else
			Notify_Line2Play=""
		fi
	fi

	# Execute the desired action
	case $1 in
    	"" | "prev" | "previous" | "Previous" | "backward")
			pw_MPDCommand previous > /dev/null 2>&1
			if [ -s /tmp/pw_daemonmode ]; then
				return 0
			fi

			;;

    	"" | "Pause" | "pause")
			pw_MPDCommand pause > /dev/null 2>&1	
			if [ -s /tmp/pw_daemonmode ]; then
				return 0
			fi

			;;

    	"" | "Play" | "play")
			pw_MPDCommand play > /dev/null 2>&1
			if [ -s /tmp/pw_daemonmode ]; then
				return 0
			fi

			;;
		
    	"" | "Stop" | "stop")
			pw_MPDCommand stop > /dev/null 2>&1
			if [ -s /tmp/pw_daemonmode ]; then
				return 0
			fi

			;;

    	"" | "Next" | "next" | "Forward" | "forward")
			pw_MPDCommand next > /dev/null 2>&1
			if [ -s /tmp/pw_daemonmode ]; then
				return 0
			fi

			;;

		*) 
			prompt="";;

	esac

	pw_Refresh
}

pw_SpawnNotification_Shortcut() {
	pw_Refresh

	if [ -z "$OPPSTATUS" ] && [ "$NEWNOTIFBEHAVIOR" = 1 ]; then
		NOTIFICATIONACTION=""
	elif [ "$NEWNOTIFBEHAVIOR" = 0 ]; then
		NOTIFICATIONACTION="--action ""$OPPSTATUS"="$OPPSTATUS"" --action forward="	
	fi

	pw_SpawnNotification "$(pw_Print "$Notify_TitlePlay")" "$(pw_Print "$Notify_Line1Play")" "$(pw_Print "$Notify_Line2Play")" "$previewname" "$OPPSTATUS" &
	return
}

pw_MenuOptions() {
	# Different dmenu routines
	sleep 0.1

    while [ "$SelectedOption" != "Close" ]
    do
        # Get the arguments for the option if the user typed any
        case "$SelectedOption" in
            *" "*) SelectedOptionArguments=${SelectedOption#* } ;;
            *)     SelectedOptionArguments="" ;;
        esac

        # Then assign the first option as the selected option..
        SelectedOption=${SelectedOption%% *}

        case $SelectedOption in
	    # Daemon option
		    "daemon")
		    # Sleep to mitigate some race conditions

			    if [ "$pw_MPDIsOnline" = "false" ]; then
				    mpd="Close"
			    elif [ -z "$OPPSTATUS2" ]; then
				    mpd=':'"$OPPSTATUS"'::seek:setvol:single:random:repeat:consume:clear:update:shuffle:crossfade'
			    else
				    mpd=':'"$OPPSTATUS:$OPPSTATUS2"'::seek:setvol:single:random:repeat:consume:clear:update:shuffle:crossfade'
			    fi

			    if [ "$CLI" = True ]; then
				    exit 0
			    fi
	
			    if [ "$pw_MPDIsOnline" = "false" ]; then
				    if [ "$UseNerdFont" = "false" ]; then
					    DMENU_TITLE="Offline"
				    else
					    DMENU_TITLE="$NOTIFYSEND_STATUS Offline"
				    fi
			    elif [ -z "$mpc_file" ]; then
				    if [ "$UseNerdFont" = "false" ]; then
					    DMENU_TITLE="Stopped"
				    else
					    DMENU_TITLE="$NOTIFYSEND_STATUS Stopped"
				    fi

			    else
				    if [ "$UseNerdFont" = "false" ]; then
					    DMENU_TITLE="$NOTIFYSEND_STATUS: "'"'"$title"'"'" by $artist"
				    else
				    	DMENU_TITLE="$NOTIFYSEND_STATUS "'"'"$title"'"'" by $artist"
			    	fi
		    	fi

	    		# Show dmenu with the controls
    			if [ -s /tmp/pw_daemonmode ]; then	
		    		prompt="$(printf '%s\n' "$mpd" | tr ':' '\n' | pw_SpawnMenu)"
	    			SelectedOption=$prompt
    			fi

		    	if [ -z "$prompt" ]; then
	    			SelectedOption="Close"
    			else
		    		SelectedOption="daemon"
	    		fi
    			;;

	    	# Different commands
    		"setvol" | "vol" | "volume" | "crossfade" | "seek")
		
			    case $SelectedOption in
				    "setvol" | "Setvol" | "vol" | "Vol" | "volume")
					    DMENU_TITLE='Set volume (0-100)'
					    SelectedOption="setvol";;
				    "seek" | "Seek")
					    DMENU_TITLE='Seek to where?'
					    SelectedOption="seek";;
				    "crossfade")
					    DMENU_TITLE='Set crossfade:'
				    	SelectedOption="crossfade";;
			    esac

			    if [ -z "$SelectedOptionArguments" ]; then
				    if [ "$pw_CurrentOperatingSystem" = "Darwin" ]; then
			    		Darwin_InsertBoxDialog=$(cat <<EOF
set userInput to display dialog "$DMENU_TITLE" default answer "" buttons {"Cancel", "OK"} default button "OK"

if button returned of userInput is "Cancel" then
    return "Cancel"
else
	set userInputText to text returned of userInput
	try
    	set userInputNumber to userInputText as number
    	set result to userInputNumber
	on error
    	set result to "" as text
	end try
end if

return result
EOF
		    )
					    prompt=$(osascript -e "$Darwin_InsertBoxDialog")
				    else
					    prompt=$(printf "Cancel" | pw_SpawnMenu)
				    fi

				    if [ "$prompt" != "Cancel" ]; then
					    pw_CLICommand "$SelectedOption" "$prompt"
				    fi

			    elif [ -n "$SelectedOptionArguments" ]; then
				    pw_CLICommand "$SelectedOption" "$SelectedOptionArguments"
			    fi
                
				pw_Refresh
                SelectedOption="MainMenu";;


		    "single" | "random" | "consume")
			    case $SelectedOption in
				    "single")
					    mpd="0:1:oneshot:Cancel";;
				    *)
				    	mpd="0:1:Cancel";;
			    esac

			    if [ -z "$SelectedOptionArguments" ]; then
				    DMENU_TITLE="Set boolean for $SelectedOption"
				    prompt="$(printf '%s\n' "$mpd" | tr ':' '\n' | pw_SpawnMenu)"
				    pw_CLICommand "$SelectedOption" "$prompt"

			    elif [ -n "$SelectedOptionArguments" ]; then
				    pw_CLICommand "$SelectedOption" "$SelectedOptionArguments"
			    fi

				pw_Refresh
                SelectedOption="MainMenu"
                ;;

		    "clear")
			    mpd="Yes:No"
			    DMENU_TITLE="Are you sure you want to clear the playlist?"
			    prompt="$(printf '%s\n' "$mpd" | tr ':' '\n' | pw_SpawnMenu)"

			    if [ $prompt == "Yes" ]; then
					pw_CLICommand "SelectedOption"
				fi

				pw_Refresh
			    SelectedOption="MainMenu";;

		    "CLI" | "cli")
			    DMENU_TITLE='Periwinkle:'

			    if [ -z "$SelectedOptionArguments" ]; then
				    prompt=$(pw_SpawnMenu)
				    pw_CLICommand "$prompt"

			    elif [ -n "$SelectedOptionArguments" ]; then
				    pw_CLICommand "$SelectedOptionArguments"
			    fi
				
				pw_Refresh
				SelectedOption="MainMenu"
				;;
			
			"$PreviousIcon" | "$OPPSTATUS" | "$OPPSTATUS2" | "$ForwardIcon")
				
					
				pw_UserSelection "$SelectedOption"

				pw_Refresh
				SelectedOption="MainMenu";;

		    # No arguments
		    "MainMenu")

		    # Show dmenu with the controls
			
			    if [ "$UseNerdFont" = true ]; then
				    PreviousIcon=""
				    ForwardIcon=""
			    else
				    PreviousIcon="Previous"
				    ForwardIcon="Next"
			    fi

			    if [ "$pw_MPDIsOnline" = "false" ]; then
				    mpd="Close"
			    elif [ -z "$OPPSTATUS2" ]; then
				    mpd="$PreviousIcon"':'"$OPPSTATUS"':'"$ForwardIcon"':seek:setvol:single:random:repeat:consume:clear:update:shuffle:crossfade:Close'

			    else
				    mpd="$PreviousIcon"':'"$OPPSTATUS:$OPPSTATUS2"':'"$ForwardIcon"':seek:setvol:single:random:repeat:consume:clear:update:shuffle:crossfade:Close'
			    fi

			    if [ "$pw_MPDIsOnline" = "false" ]; then
				    if [ "$UseNerdFont" = "false" ]; then
					    DMENU_TITLE="Offline"
				    else
					    DMENU_TITLE="$NOTIFYSEND_STATUS Offline"
				    fi
			    elif [ -z "$mpc_file" ]; then
				    if [ "$UseNerdFont" = "false" ]; then
					    DMENU_TITLE="Stopped"
				    else
					    DMENU_TITLE="$NOTIFYSEND_STATUS Stopped"
				    fi

			    else
				    if [ "$UseNerdFont" = "false" ]; then
					    DMENU_TITLE="$NOTIFYSEND_STATUS: "'"'"$title"'"'" by $artist"
				    else
					    DMENU_TITLE="$NOTIFYSEND_STATUS "'"'"$title"'"'" by $artist"
				    fi
			    fi

			    prompt="$(printf '%s\n' "$mpd" | tr ':' '\n' | pw_SpawnMenu)"
			    SelectedOption=$prompt
			    if [ -z "$prompt" ]; then
				    SelectedOption="Close"
			    fi
                ;;
	    esac

    done
	
}

pw_QuitDaemon() {
	pw_SendMessage Info "Quitting..."
	rm /tmp/pw_daemonmode
	exit 0
}

pw_Nothing() {
	true
}

pw_PeriwinkleDaemon() {		
	printf 'Daemon Mode' > /tmp/pw_daemonmode
	pw_Refresh
	trap pw_QuitDaemon INT
	trap pw_QuitDaemon TERM
	trap pw_Nothing HUP
	currentsong_daemon="$title - $artist - $album $date $mpc_file"
	previoussong_daemon="$currentsong_daemon"
	currentstate2="$state"
	previousstate2="$currentstate2"
	pw_OnlineFuse="$pw_MPDIsOnline"

	pw_SendMessage Info "You're now running Periwinkle as a daemon!"
	pw_SendMessage Info "This feature is still experimental."
	pw_SendMessage Info "Please open an issue at https://github.com/fluffeon/periwinkle/issues if you have problems."

	if [ "$pw_MPDIsOnline" = "false" ]; then
		pw_SendMessage Warn "The Music Player Daemon is currently not running. Check if it's running."
	fi

	while true; do
		sleep 0.1
		if [ "$pw_OnlineFuse" != "$pw_MPDIsOnline" ] && [ "$pw_MPDIsOnline" = "false" ]; then
			pw_SendMessage Warn "The Music Player Daemon is currently not running. Check if it's running."
			pw_OnlineFuse=$pw_MPDIsOnline
			pw_SpawnNotification_Shortcut
		elif [ "$pw_OnlineFuse" != "$pw_MPDIsOnline" ] && [ "$pw_MPDIsOnline" = "true" ]; then
			pw_SendMessage Info "The Music Player Daemon has started."
			pw_OnlineFuse=$pw_MPDIsOnline
			pw_SpawnNotification_Shortcut
		fi

		if [ "$currentsong_daemon" != "$previoussong_daemon" ] \
		|| [ "$currentstate2" != "$previousstate2" ] && [ "$state" != "" ]; then
			if [ -z "$mpc_file" ]; then
				pw_SendMessage Info "$state: The playlist is stopped."
			else
				pw_SendMessage Info "$state: $title by $artist"
			fi
			sleep 0.1
			pw_SpawnNotification_Shortcut
			previoussong_daemon="$currentsong_daemon"
			previousstate2="$currentstate2"
		fi

		pw_Refresh
		sleep 0.5
		if [ "$pw_CurrentOperatingSystem" = "Darwin" ]; then
			pw_Counter=0

			while true; do
				pw_Refresh
				if [ -n "$mpc_file" ] || [ "$pw_Counter" -eq 10 ]; then
					break
				fi
				pw_Counter=$(($pw_Counter + 1))
				sleep 0.03
			done
		fi

		if [ "$pw_MPDIsOnline" = "false" ]; then
			Notify_TitlePlay="$Notify_TitleOffline"
			Notify_Line1Play=""
			if [ "$pw_CurrentOperatingSystem" = "Darwin" ]; then
				Notify_Line2Play="The Music Player Daemon is currently not running."
			else
				Notify_Line2Play=""
			fi
		elif [ -z "$mpc_file" ]; then
			Notify_TitlePlay="$Notify_TitleStop"
			Notify_Line1Play=""
			if [ "$pw_CurrentOperatingSystem" = "Darwin" ]; then
				Notify_Line2Play="The playlist is currently stopped."
			else
				Notify_Line2Play=""
			fi
		else
			Notify_TitlePlay=$Notify_TitlePlaySave
			Notify_Line1Play=$Notify_Line1PlaySave
			Notify_Line2Play=$Notify_Line2PlaySave
		fi 
		
		mpc_file="$(printf "%s" "$stats" | awk -F ': ' '/^file:/ {print $2}' | awk '{$1=$1};1')" 
		currentsong_daemon="$title - $artist - $album $date $mpc_file"
		currentstate2="$state"
	done
}

pw_Print() {
	pw_Refresh

	case $FORMATCLI in
		"TRUE")
			title="$titlesave"
			artist="$artistsave"
	esac

	input_arguments="$*"

	# Trim leading space and output the captured input arguments
	input_arguments="${input_arguments# }"
	output_text=$(printf "%s" "$input_arguments" | awk -v titlevar="$title" \
													   -v artistvar="$artist" \
													   -v albumvar="$album" \
													   -v datevar="$unprocesseddate" \
													   -v datepvar="$date" \
													   -v statevar="$state" \
													   -v stateiconvar="$NOTIFYSEND_STATUS" \
													   -v songidvar="$songid" \
													   -v filenamevar="$mpc_file" \
													   -v dirvar="$filename" \
													   -v durationvar="$totalduration" \
                            						   -v timevar="$elapsedtime" '{
	  gsub(/%title%/, titlevar);
	  gsub(/%artist%/, artistvar);
	  gsub(/%album%/, albumvar);
	  gsub(/%date%/, datevar);
	  gsub(/%datep%/, datepvar);
	  gsub(/%state%/, statevar);
	  gsub(/%stateicon%/, stateiconvar);
	  gsub(/%songid%/, songidvar);
	  gsub(/%filename%/, filenamevar);
	  gsub(/%dir%/, dirvar);
      gsub(/%time%/, timevar);
	  gsub(/%duration%/, durationvar);
	  print;
	}')
	printf "%s" "$output_text"
}

# CLI actions
pw_CLICommand() {
	pw_Refresh
	case $1 in
		"help") pw_Help;;

		"pause" | "play" | "prev" | "previous" \
		| "backward" | "stop" | "next" | "forward")
			CLI=True
			pw_UserSelection "$1";;

		"menu") pw_MenuOptions MainMenu &;;

		"daemon") pw_PeriwinkleDaemon;;

		"clear" | "update" | "shuffle" | "playlist")
			if [ -z "$2" ]; then
				pw_MPDCommandButFiltered "$*";
			else
				pw_SendMessage ErrManyArguments
			fi;;

		"add" | "rm" | "find" | "save" | "setvol" \
		| "list" | "crossfade" | "single" | "random" \
		| "consume" | "repeat" | "delete" | "direct")
			if [ "$1" = "direct" ]; then
				pw_MPDCommandButFiltered "$2" "$3" "$4" "$5"
			elif [ -n "$2" ]; then
				pw_MPDCommandButFiltered "$1" "$2" "$3" "$4" "$5"
			else
				pw_SendMessage ErrFewArguments
			fi;;
		"seek")
			if [ -n "$3" ]; then
				pw_SendMessage ErrManyArguments
			fi

			if [ -z "$songid" ]; then
				pw_SendMessage ErrPlaylistClear "$1"
			fi

			if [ -n "$2" ]; then
				MINIMUMVAL=-1 MAXIMUMVAL=2147483648 pw_CheckNumber "$2" inRange
				pw_MPDCommandButFiltered seek "$songid" "$2"
			else
				pw_SendMessage ErrFewArguments
			fi;;

		"format" | "print")
			FORMATCLI=TRUE
			shift
			pw_Print "$@";;

		"clearpreviews")
			rm "$Directory_AlbumCover"/*.png;;

		"statsfornerds")
			pw_Refresh SetAlbumCover
			pw_SendMessage Info "Output:"
			pw_SendMessage Info "$stats"
			pw_SendMessage Info "Preview Dir: $Directory_AlbumCover"
			pw_SendMessage Info "Filename: $filename" 
			pw_SendMessage Info "Preview Name: $previewname" 
			pw_SendMessage Info "Title: $title" 
			pw_SendMessage Info "Artist: $artist"
			pw_SendMessage Info "Album: $album"
			pw_SendMessage Info "Date: $date"
			pw_SendMessage Info "Hash: $UseHash"
			pw_SendMessage Info "DMENU SETTINGS: $Bar_Position $DMENU_TITLE $Bar_Font $Color_Background \
												 $Color_Foreground $Color_SelectedBackground $Color_SelectedForeground";;

		"console") nc "$MPD_Host" "$MPD_Port";;
		
		"info") pw_AboutProgram;;
		
		"")

		if [ "$pw_MPDIsOnline" = "false" ]; then
			Notify_TitlePlay="$Notify_TitleOffline"
			Notify_Line1Play=""
			if [ "$pw_CurrentOperatingSystem" = "Darwin" ]; then
				Notify_Line2Play="The Music Player Daemon is currently not running."
			else
				Notify_Line2Play=""
			fi
		elif [ -z "$mpc_file" ] && [ "$pw_MPDIsOnline" = "true" ]; then
			Notify_TitlePlay="$Notify_TitleStop"
			Notify_Line1Play=""
			if [ "$pw_CurrentOperatingSystem" = "Darwin" ]; then
				Notify_Line2Play="The playlist is currently stopped."
			else
				Notify_Line2Play=""
			fi
		fi

		pw_SpawnNotification_Shortcut;;
		
		*) pw_SendMessage ErrUnknownCommand "$1";;
	esac
}

pw_CurrentOperatingSystem=$(uname)

#printf "$pw_CurrentOperatingSystem" | grep BSD
#
#if [ $? -eq 1 ]; then
#	case "$pw_CurrentOperatingSystem" in
#		"Linux" | "SunOS" | "Darwin")
#			true;;
#		*)
#			pw_SendMessage Warn "Your operating system ($pw_CurrentOperatingSystem) is not on the \
#								 list of known operating systems supported by Periwinkle, here be dragons.";;
#	esac
#fi

# Core dependencies
pw_DependencyList="nc awk ffmpeg uname"

# OS-specific dependencies
if [ "$pw_CurrentOperatingSystem" = "Darwin" ]; then
	alias sha256sum="shasum -a 256"
	alias sha512sum="shasum -a 512"
	alias md5sum="md5"
	pw_DependencyList="$pw_DependencyList alerter dmenu-mac"
else
	pw_DependencyList="$pw_DependencyList notify-send"
fi

if [ "$UseThisMenuProgram" = "wmenu" ] && [ "$pw_CurrentOperatingSystem" != "Darwin" ]; then
	pw_DependencyList="$pw_DependencyList wmenu"
elif [ "$UseThisMenuProgram" = "dmenu" ] && [ "$pw_CurrentOperatingSystem" != "Darwin" ]; then
	pw_DependencyList="$pw_DependencyList dmenu"
fi

pw_DependencyListLen=${#pw_DependencyList}

pw_DependencyListLen=$((pw_DependencyListLen + 2))

# Initialize index
pw_PositionedIn=1

# Iterate over each character in the string to find the missing dependencies.
while [ "$pw_PositionedIn" -lt "$pw_DependencyListLen" ]; do
	pw_CurrentChar="$(printf "%s\n" "$pw_DependencyList\n" | cut -c $pw_PositionedIn)"
    pw_PositionedIn=$((pw_PositionedIn + 1))

	if [ "$pw_CurrentChar" = " " ] || [ $pw_PositionedIn -eq $pw_DependencyListLen ]; then
		for cmd in $pw_AuxiliarAppend; do
    		if ! command -v "$cmd" > /dev/null 2>&1; then
				pw_SendMessage Error "Missing dependency: $cmd"
				pw_ThereIsOneDependencyMissing="true"
    		fi
		done
		pw_AuxiliarAppend=""
	else
		pw_AuxiliarAppend="$pw_AuxiliarAppend""$pw_CurrentChar"
	fi

done

if [ "$pw_ThereIsOneDependencyMissing" = "true" ]; then
	exit 1
fi

pw_FillInTheBlanks

case $Notify_FillEmptyTags in
	"true")
	FORMATCLI="TRUE"
	;;
esac

case $Notify_ExtraButtons in
	"true")
	NEWNOTIFBEHAVIOR=0;;
	"false")
	NEWNOTIFBEHAVIOR=1
	;;
esac	

# Checks if MPD_Port is a valid number that IS an integer and NOT a string
MINIMUMVAL=1 MAXIMUMVAL=65535 pw_CheckNumber "$MPD_Port" inRange
pw_CheckNumber "$Notify_Timeout" isPositive

# Checks if Notify_Timeout is a valid number that is NOT a string, but independently if it's an integer

if [ ! -d "$Directory_AlbumCover" ]; then
	mkdir -v "$Directory_AlbumCover"
fi

# The config checking routines were made by ChatGPT. Thank you so much.

# Convert the seconds to milliseconds in the Notify_Timeout variable
Notify_Timeout=$(awk "BEGIN { printf(\"%.0f\", $Notify_Timeout * 1000) }" | awk '{sub(/%$/,"")}1')

pw_ReloadMetadata All

pw_Refresh

# Fetch some stuff, better not change this
mpc_file="$(printf "%s" "$stats" | awk -F ': ' '/^file:/ {print $2}' | awk '{$1=$1};1')"
filename=$Directory_MusicFolder/${mpc_file##*:}

case $Bar_Position in
	"bottom" | "Bottom")
		Bar_Position="-b"
		;;
	"top" | "Top")
		Bar_Position="-f"
		;;
	*)
	Bar_Position="-b"
		;;
esac

pw_CLICommand "$@"
